// function random_number_in_a_Range(max, min) {
//   const result = Math.floor(Math.random() * (max - min + 1) + min);
//   return result;
// }

// const result = random_number_in_a_Range(3, 1);

const result = Math.floor(Math.random() * 3);
console.log(result);
function computerSelection(result) {
  switch (result) {
    case 1:
      return "stone";
      break;
    case 2:
      return "paper";
      break;
    default:
      return "scissor";
      break;
  }
}

const computerSelectionResult = computerSelection(result);

// insted of switch statement we can do this one line as well
// let computerSelectionResult = ["S", "W", "G"][cpuI];
/*
let cpu = ["S", "W", "G"][cpuI];

["S", "W", "G"] is an array containing the options "S", "W", and "G".
cpuI is used as an index to access one of these options from the array:
If cpuI is 0, cpu will be "S".
If cpuI is 1, cpu will be "W".
If cpuI is 2, cpu will be "G".
Therefore, cpu will randomly hold one of these values based on the random index generated by Math.random().
*/

console.log(computerSelectionResult);

let userInput = prompt("Type stone , paper or scissor ");

console.log(userInput);

// Using if-else statements to determine the winner
if (userInput === computerSelectionResult) {
  alert("Tie !!");
} else if (
  (userInput === "stone" && computerSelectionResult === "scissor") ||
  (userInput === "paper" && computerSelectionResult === "stone") ||
  (userInput === "scissor" && computerSelectionResult === "paper")
) {
  alert("You Won !!");
} else {
  alert("You Lost !!");
}
